apiVersion: apps/v1
kind: Deployment
metadata:
  name: drplan-app-deployment
  namespace: drplan-app
  labels:
    app: drplan
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: drplan
  template:
    metadata:
      labels:
        app: drplan
    spec:
      imagePullSecrets:
        - name: acr-secret    # 시크릿 이름도 올바르게 설정
      containers:
        - name: drplan-app-container
          image: drplanacrrepo.azurecr.io/drplan-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

