apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drplan-ingress
  namespace: drplan-app
  labels:
    app: drplan
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drplan-service
            port:
              number: 8080
      - path: /index.jsp
        pathType: Prefix
        backend:
          service:
            name: drplan-service
            port:
              number: 8080
      - path: /contents
        pathType: Prefix
        backend:
          service:
            name: drplan-service
            port:
              number: 8080

