apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- DrPlan-deployment.yaml
- DrPlan-service.yaml
- DrPlan-ingress.yaml

images:
- name: drplanacrrepo.azurecr.io/drplan-app
  newTag: 772fd386-1746524227
