apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- DrPlan-deployment.yaml
- DrPlan-service.yaml
- DrPlan-ingress.yaml
- alb-ingress-class.yaml
- fluentbit-configmap.yaml
- fluentbit-serviceaccount.yaml
- fluentbit-daemonset.yaml
images:
- name: 253490772403.dkr.ecr.ap-northeast-2.amazonaws.com/drplan-ecr-seoul-repo
  newName: 253490772403.dkr.ecr.ap-northeast-2.amazonaws.com/drplan-ecr-seoul-repo
  newTag: f3fdf2f9-1746270240
